schema_version = 3

[project]
uuid = "ef81b740-6e31-44bd-8b30-74be81bd1f48"
name = "readio"

[ledgers.taskledger.mounts.data]
storage = "external"
root = "../ledger"

[ledgers.taskledger.mounts.runtime]
storage = "user-data"

[ledgers.taskledger.mounts.logs]
storage = "user-data"

[ledgers.taskledger.mounts.indexes]
storage = "cache"

[ledgers.releaseledger.mounts.data]
storage = "project"

[ledgers.releaseledger.mounts.indexes]
storage = "cache"

[ledgers.documentledger.mounts.data]
storage = "project"

[ledgers.documentledger.mounts.artifacts]
storage = "cache"
